/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  APIsSidebar: [
    {
      type: 'category',
      label: 'Ally',
      items: [
        'allyapisintro',
        'apis/ally/allyapis'
      ]
    },
    {
      type: 'category',
      label: 'Learn',
      items: [
        'learnapisintro',
        'apis/learn/learnapisreleased',
        'apis/learn/learnapisunreleased'
      ]
    },
    {
      type: 'category',
      label: 'Student',
      items: [
        'studentapisintro',
        {
          type: 'autogenerated',
          dirName: 'apis/student', // Generate sidebar slice from docs path
        },
      ]
    },
  ],
  StudentAPIsSidebar: [
    'studentapisintro',
    {
      type: 'category',
      label: 'Student APIs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'apis/student', // Generate sidebar slice from docs path
        },
      ]
    }
  ],
  LearnAPIsSidebar: [
    'learnapisintro',
    'apis/learn/learnapisreleased',
    'apis/learn/learnapisunreleased'
    // {
    //   type: 'category',
    //   label: 'LEARN APIs',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'apis/learn'
    //     },
    //   ]
    // }
  ],
  AllyAPIsSidebar: [
    'allyapisintro',
    'apis/ally/allyapis'
  ]

};

module.exports = sidebars;
