/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  APIsSidebar: [
    {
      type: 'category',
      label: 'Ally',
      items: [
        'allyapisintro',
        'apis/ally/allyapis'
      ]
    },
    {
      type: 'category',
      label: 'Learn',
      items: [
        'learnapisintro',
        'apis/learn/learnapisreleased',
        'apis/learn/learnapisunreleased'
      ]
    },
    {
      type: 'category',
      label: 'Student',
      items: [
        'studentapisintro',
        {
          type: 'autogenerated',
          dirName: 'apis/student', // Generate sidebar slice from docs path
        },
      ]
    },
  ],
  StudentAPIsSidebar: [
    'studentapisintro',
    {
      type: 'category',
      label: 'Student APIs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'apis/student', // Generate sidebar slice from docs path
        },
      ]
    }
  ],
  StudentRapidocsAPIsSidebar: [
    'rapidocs/student/studentredocsapisintro',
    {
      type: 'category',
      label: 'Student APIs',
      items: [
        {
          type: 'link',
          label: 'Academics',
          href: 'http://localhost:3000/studentapiredox/api-specs/student/academics.html'
        },
        {
          type: 'link',
          label: 'Admissions',
          href: 'http://localhost:3000/studentapiredox/api-specs/student/admissions.html'
        },
        {
          type: 'link',
          label: 'Career Services',
          href: 'http://localhost:3000/studentapiredox/api-specs/student/careerservices.html'
        },
        {
          type: 'link',
          label: 'Common',
          href: 'http://localhost:3000/studentapiredox/api-specs/student/common.html'
        },
        {
          type: 'link',
          label: 'CRM',
          href: 'http://localhost:3000/studentapiredox/api-specs/student/crm.html'
        },
        {
          type: 'link',
          label: 'Financial Aid',
          href: 'http://localhost:3000/studentapiredox/api-specs/student/financialaid.html'
        },
        {
          type: 'link',
          label: 'Student Accounts',
          href: 'http://localhost:3000/studentapiredox/api-specs/student/studentaccounts.html'
        },
      ]
    }
  ],
  LearnAPIsSidebar: [
    'learnapisintro',
    'apis/learn/learnapisreleased',
    'apis/learn/learnapisunreleased'
  ],
  LearnRapidocsAPIsSidebar: [
    'rapidocs/learn/learnapisintro',
    {
      type: 'category',
      label: 'Learn Released',
      items: [
        {
          type: 'link',
          label: 'Learn Released',
          href: 'http://localhost:3000/studentapiredox/api-specs/learn/learn-released.html',
        }
      ],
    },
    {
      type: 'category',
      label: 'Learn Unreleased',
      items: [
        {
          type: 'link',
          label: 'Learn Uneleased',
          href: 'http://localhost:3000/studentapiredox/api-specs/learn/learn-unreleased.html',
        },
      ],
    }
  ],
  AllyAPIsSidebar: [
    'allyapisintro',
    'apis/ally/allyapis'
  ],
  AllyRedocsAPIsSidebar: [
    'rapidocs/ally/allyapisintro',
    {
      type: 'link',
      label: 'Ally APIs',
      href: 'http://localhost:3000/studentapiredox/api-specs/ally/ally-released.html',
    },
  ],

  RapidoxAPIsSidebar: [
    'rapidocs/rapidoxapis',
    {
      type: 'category',
      label: 'APIs',
      items: [
        {
          type: 'category',
          label: 'Ally',
          items: [
            'rapidocs/ally/allyapisintro',
            {
              type: 'link',
              label: 'Ally APIs',
              href: 'http://localhost:3000/studentapiredox/api-specs/ally/ally-released.html',
            },
          ]

        },
        {
          type: 'category',
          label: 'Learn',
          items: [
            'rapidocs/learn/learnapisintro',
            {
              type: 'link',
              label: 'Learn Released',
              href: 'http://localhost:3000/studentapiredox/api-specs/learn/learn-released.html',
            
            },
            {
              type: 'link',
              label: 'Learn Uneleased',
              href: 'http://localhost:3000/studentapiredox/api-specs/learn/learn-unreleased.html',
            },
          ]
        },
        {
          type: 'category',
          label: 'Student',
          items: [
            'rapidocs/student/studentredocsapisintro',
            {
              type: 'category',
              label: 'Student APIs',
              items: [
                {
                  type: 'link',
                  label: 'Academics',
                  href: 'http://localhost:3000/studentapiredox/api-specs/student/academics.html'
                },
                {
                  type: 'link',
                  label: 'Admissions',
                  href: 'http://localhost:3000/studentapiredox/api-specs/student/admissions.html'
                },
                {
                  type: 'link',
                  label: 'Career Services',
                  href: 'http://localhost:3000/studentapiredox/api-specs/student/careerservices.html'
                },
                {
                  type: 'link',
                  label: 'Common',
                  href: 'http://localhost:3000/studentapiredox/api-specs/student/common.html'
                },
                {
                  type: 'link',
                  label: 'CRM',
                  href: 'http://localhost:3000/studentapiredox/api-specs/student/crm.html'
                },
                {
                  type: 'link',
                  label: 'Financial Aid',
                  href: 'http://localhost:3000/studentapiredox/api-specs/student/financialaid.html'
                },
                {
                  type: 'link',
                  label: 'Student Accounts',
                  href: 'http://localhost:3000/studentapiredox/api-specs/student/studentaccounts.html'
                },
              ]
            }
          ]

        },

      ]
    }
  ]

};

module.exports = sidebars;
