openapi: 3.0.3
info:
  title: Enrollment Status
  description: All API calls related to Enrollment Status.
  contact:
    name: Anthology, Inc.
    url: https://www.anthology.com
    email: support@anthology.com
  version: "1.0"
servers:
  - url: https://localhost/Cmc.Nexus.Web
paths:
  /api/commands/Academics/EnrollmentStatus/create:
    $ref: ./paths/api_commands_Academics_EnrollmentStatus_create.yaml
  /api/commands/Academics/EnrollmentStatus/delete:
    $ref: ./paths/api_commands_Academics_EnrollmentStatus_delete.yaml
  /api/commands/Academics/EnrollmentStatus/get:
    $ref: ./paths/api_commands_Academics_EnrollmentStatus_get.yaml
  /api/commands/Academics/EnrollmentStatus/save:
    $ref: ./paths/api_commands_Academics_EnrollmentStatus_save.yaml
  /api/commands/Academics/EnrollmentStatus/saveNew:
    $ref: ./paths/api_commands_Academics_EnrollmentStatus_saveNew.yaml