openapi: 3.0.3
info:
  title: School Start Date
  description: All API calls related to School Start Dates.
  contact:
    name: Anthology, Inc.
    url: https://www.anthology.com
    email: support@anthology.com
  version: "1.0"
servers:
  - url: https://localhost/Cmc.Nexus.Web
paths:
  /api/commands/Academics/SchoolStartDate/create:
    $ref: ./paths/api_commands_Academics_SchoolStartDate_create.yaml
  /api/commands/Academics/SchoolStartDate/delete:
    $ref: ./paths/api_commands_Academics_SchoolStartDate_delete.yaml
  /api/commands/Academics/SchoolStartDate/get:
    $ref: ./paths/api_commands_Academics_SchoolStartDate_get.yaml
  /api/commands/Academics/SchoolStartDate/save:
    $ref: ./paths/api_commands_Academics_SchoolStartDate_save.yaml
  /api/commands/Academics/SchoolStartDate/saveDeactivateStartsDate:
    $ref: ./paths/api_commands_Academics_SchoolStartDate_saveDeactivateStartsDate.yaml
  /api/commands/Academics/SchoolStartDate/saveNew:
    $ref: ./paths/api_commands_Academics_SchoolStartDate_saveNew.yaml