openapi: 3.0.3
info:
  title: Enrollment Status
  description: All API calls related to Enrollment Status.
  contact:
    name: Anthology, Inc.
    url: https://www.anthology.com
    email: support@anthology.com
  version: '1.0'
servers:
  - url: https://localhost/Cmc.Nexus.Web
paths:
  /api/commands/Academics/EnrollmentStatus/create:
    post:
      tags:
        - EnrollmentStatus
      summary: Create Enrollment Status
      operationId: academics-enrollmentstatus-create
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/academics-enrollmentstatus-create-response'
  /api/commands/Academics/EnrollmentStatus/delete:
    post:
      tags:
        - EnrollmentStatus
      summary: Delete Enrollment Status
      operationId: academics-enrollmentstatus-delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/academics-enrollmentstatus-delete-request'
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/academics-enrollmentstatus-delete-response'
  /api/commands/Academics/EnrollmentStatus/get:
    post:
      tags:
        - EnrollmentStatus
      summary: Get Enrollment Status
      operationId: academics-enrollmentstatus-get
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/academics-enrollmentstatus-get-request'
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/academics-enrollmentstatus-get-response'
  /api/commands/Academics/EnrollmentStatus/save:
    post:
      tags:
        - EnrollmentStatus
      summary: Save Enrollment Status
      operationId: academics-enrollmentstatus-save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/academics-enrollmentstatus-save-request'
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/academics-enrollmentstatus-save-response'
  /api/commands/Academics/EnrollmentStatus/saveNew:
    post:
      tags:
        - EnrollmentStatus
      summary: Save New Enrollment Status
      operationId: academics-enrollmentstatus-savenew
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/academics-enrollmentstatus-savenew-request'
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/academics-enrollmentstatus-savenew-response'
components:
  schemas:
    academics-enrollmentstatus-create-response-payload-data:
      description: ''
      required:
        - id
        - code
        - createdDateTime
        - lastModifiedDateTime
        - lastModifiedUserId
        - name
      properties:
        id:
          format: int32
          description: Id
          type: number
        code:
          description: Code
          type: string
        createdDateTime:
          format: date-time
          description: Created Date Time
          type: string
        isActive:
          description: Is Active
          type: boolean
        isSystemCode:
          description: Is System Code
          type: boolean
        lastModifiedDateTime:
          format: date-time
          description: Last Modified Date Time
          type: string
        lastModifiedUserId:
          format: int32
          description: Last Modified User Id
          type: number
        minimumCreditHours:
          description: Minimum Credit Hours
          type: object
        name:
          description: Name
          type: string
        rowVersion:
          type: string
        originalState:
          type: string
        secureState:
          type: string
        extendedProperties:
          type: array
          items: {}
        entityState:
          format: int32
          type: number
    academics-enrollmentstatus-create-response-payload:
      properties:
        data:
          $ref: '#/components/schemas/academics-enrollmentstatus-create-response-payload-data'
    academics-enrollmentstatus-create-response:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-create-response-payload'
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
    academics-enrollmentstatus-delete-request-payload:
      description: ''
      properties:
        id:
          format: int32
          description: Id
          type: number
        code:
          description: Code
          type: string
        createdDateTime:
          format: date-time
          description: Created Date Time
          type: string
        isActive:
          description: Is Active
          type: boolean
        isSystemCode:
          description: Is System Code
          type: boolean
        lastModifiedDateTime:
          format: date-time
          description: Last Modified Date Time
          type: string
        lastModifiedUserId:
          format: int32
          description: Last Modified User Id
          type: number
        minimumCreditHours:
          description: Minimum Credit Hours
          type: object
        name:
          description: Name
          type: string
        rowVersion:
          type: string
        originalState:
          type: string
        secureState:
          type: string
        extendedProperties:
          type: array
          items: {}
        entityState:
          format: int32
          type: number
    academics-enrollmentstatus-delete-request:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-delete-request-payload'
    academics-enrollmentstatus-delete-response-payload:
      properties:
        deleted:
          type: boolean
    academics-enrollmentstatus-delete-response:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-delete-response-payload'
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
    academics-enrollmentstatus-get-request-payload:
      description: ''
      properties:
        id:
          format: int32
          type: number
    academics-enrollmentstatus-get-request:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-get-request-payload'
    academics-enrollmentstatus-get-response-payload-data:
      description: ''
      required:
        - id
        - code
        - createdDateTime
        - lastModifiedDateTime
        - lastModifiedUserId
        - name
      properties:
        id:
          format: int32
          description: Id
          type: number
        code:
          description: Code
          type: string
        createdDateTime:
          format: date-time
          description: Created Date Time
          type: string
        isActive:
          description: Is Active
          type: boolean
        isSystemCode:
          description: Is System Code
          type: boolean
        lastModifiedDateTime:
          format: date-time
          description: Last Modified Date Time
          type: string
        lastModifiedUserId:
          format: int32
          description: Last Modified User Id
          type: number
        minimumCreditHours:
          description: Minimum Credit Hours
          type: object
        name:
          description: Name
          type: string
        rowVersion:
          type: string
        originalState:
          type: string
        secureState:
          type: string
        extendedProperties:
          type: array
          items: {}
        entityState:
          format: int32
          type: number
    academics-enrollmentstatus-get-response-payload:
      properties:
        data:
          $ref: '#/components/schemas/academics-enrollmentstatus-get-response-payload-data'
    academics-enrollmentstatus-get-response:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-get-response-payload'
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
    academics-enrollmentstatus-save-request-payload:
      description: ''
      properties:
        id:
          format: int32
          description: Id
          type: number
        code:
          description: Code
          type: string
        createdDateTime:
          format: date-time
          description: Created Date Time
          type: string
        isActive:
          description: Is Active
          type: boolean
        isSystemCode:
          description: Is System Code
          type: boolean
        lastModifiedDateTime:
          format: date-time
          description: Last Modified Date Time
          type: string
        lastModifiedUserId:
          format: int32
          description: Last Modified User Id
          type: number
        minimumCreditHours:
          description: Minimum Credit Hours
          type: object
        name:
          description: Name
          type: string
        rowVersion:
          type: string
        originalState:
          type: string
        secureState:
          type: string
        extendedProperties:
          type: array
          items: {}
        entityState:
          format: int32
          type: number
    academics-enrollmentstatus-save-request:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-save-request-payload'
    academics-enrollmentstatus-save-response-payload-data:
      description: ''
      required:
        - id
        - code
        - createdDateTime
        - lastModifiedDateTime
        - lastModifiedUserId
        - name
      properties:
        id:
          format: int32
          description: Id
          type: number
        code:
          description: Code
          type: string
        createdDateTime:
          format: date-time
          description: Created Date Time
          type: string
        isActive:
          description: Is Active
          type: boolean
        isSystemCode:
          description: Is System Code
          type: boolean
        lastModifiedDateTime:
          format: date-time
          description: Last Modified Date Time
          type: string
        lastModifiedUserId:
          format: int32
          description: Last Modified User Id
          type: number
        minimumCreditHours:
          description: Minimum Credit Hours
          type: object
        name:
          description: Name
          type: string
        rowVersion:
          type: string
        originalState:
          type: string
        secureState:
          type: string
        extendedProperties:
          type: array
          items: {}
        entityState:
          format: int32
          type: number
    academics-enrollmentstatus-save-response-payload:
      properties:
        data:
          $ref: '#/components/schemas/academics-enrollmentstatus-save-response-payload-data'
    academics-enrollmentstatus-save-response:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-save-response-payload'
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
    academics-enrollmentstatus-savenew-request-payload:
      description: ''
      properties:
        id:
          format: int32
          description: Id
          type: number
        code:
          description: Code
          type: string
        createdDateTime:
          format: date-time
          description: Created Date Time
          type: string
        isActive:
          description: Is Active
          type: boolean
        isSystemCode:
          description: Is System Code
          type: boolean
        lastModifiedDateTime:
          format: date-time
          description: Last Modified Date Time
          type: string
        lastModifiedUserId:
          format: int32
          description: Last Modified User Id
          type: number
        minimumCreditHours:
          description: Minimum Credit Hours
          type: object
        name:
          description: Name
          type: string
        rowVersion:
          type: string
        originalState:
          type: string
        secureState:
          type: string
        extendedProperties:
          type: array
          items: {}
        entityState:
          format: int32
          type: number
    academics-enrollmentstatus-savenew-request:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-savenew-request-payload'
    academics-enrollmentstatus-savenew-response-payload-data:
      description: ''
      required:
        - id
        - code
        - createdDateTime
        - lastModifiedDateTime
        - lastModifiedUserId
        - name
      properties:
        id:
          format: int32
          description: Id
          type: number
        code:
          description: Code
          type: string
        createdDateTime:
          format: date-time
          description: Created Date Time
          type: string
        isActive:
          description: Is Active
          type: boolean
        isSystemCode:
          description: Is System Code
          type: boolean
        lastModifiedDateTime:
          format: date-time
          description: Last Modified Date Time
          type: string
        lastModifiedUserId:
          format: int32
          description: Last Modified User Id
          type: number
        minimumCreditHours:
          description: Minimum Credit Hours
          type: object
        name:
          description: Name
          type: string
        rowVersion:
          type: string
        originalState:
          type: string
        secureState:
          type: string
        extendedProperties:
          type: array
          items: {}
        entityState:
          format: int32
          type: number
    academics-enrollmentstatus-savenew-response-payload:
      properties:
        data:
          $ref: '#/components/schemas/academics-enrollmentstatus-savenew-response-payload-data'
    academics-enrollmentstatus-savenew-response:
      properties:
        payload:
          $ref: '#/components/schemas/academics-enrollmentstatus-savenew-response-payload'
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
