openapi: 3.0.3
info:
  title: Areas of Study
  description: All API calls related to Areas of Study.
  contact:
    name: Anthology, Inc.
    url: https://www.anthology.com
    email: support@anthology.com
  version: "1.0"
servers:
  - url: https://localhost/Cmc.Nexus.Web
security:
  - apikey: []
paths:
  /api/commands/Academics/AreaOfStudy/create:
    $ref: ./paths/api_commands_Academics_AreaOfStudy_create.yaml
  /api/commands/Academics/AreaOfStudy/delete:
    $ref: ./paths/api_commands_Academics_AreaOfStudy_delete.yaml
  /api/commands/Academics/AreaOfStudy/get:
    $ref: ./paths/api_commands_Academics_AreaOfStudy_get.yaml
  /api/commands/Academics/AreaOfStudy/save:
    $ref: ./paths/api_commands_Academics_AreaOfStudy_save.yaml
  /api/commands/Academics/AreaOfStudy/saveNew:
    $ref: ./paths/api_commands_Academics_AreaOfStudy_saveNew.yaml
