openapi: 3.0.3
info:
  title: Additional Gpa
  description: All API calls related to Additional Gpa.
  contact:
    name: Anthology, Inc.
    url: https://www.anthology.com
    email: support@anthology.com
  version: '1.0'
servers:
  - url: https://localhost/Cmc.Nexus.Web
paths:
  /api/commands/Academics/AdditionalGpa/getGpaCourse:
    post:
      tags:
        - AdditionalGpa
      summary: Get Gpa Course
      operationId: academics-additionalgpa-getgpacourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/academics-additionalgpa-getgpacourse-request
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/academics-additionalgpa-getgpacourse-response
  /api/commands/Academics/AdditionalGpa/getStudentGpa:
    post:
      tags:
        - AdditionalGpa
      summary: Get Student Gpa
      operationId: academics-additionalgpa-getstudentgpa
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/academics-additionalgpa-getstudentgpa-request
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/academics-additionalgpa-getstudentgpa-response
  /api/commands/Academics/AdditionalGpa/recalculateGpa:
    post:
      tags:
        - AdditionalGpa
      summary: Recalculate Gpa
      operationId: academics-additionalgpa-recalculategpa
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/academics-additionalgpa-recalculategpa-request
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/academics-additionalgpa-recalculategpa-response
  /api/commands/Academics/AdditionalGpa/saveGpaCourse:
    post:
      tags:
        - AdditionalGpa
      summary: Save Gpa Course
      operationId: academics-additionalgpa-savegpacourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/academics-additionalgpa-savegpacourse-request
        description: Payload for the command
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/academics-additionalgpa-savegpacourse-response
components:
  schemas:
    academics-additionalgpa-getgpacourse-request-payload:
      description: ''
      properties:
        studentId:
          format: int32
          type: number
        gpaId:
          format: int32
          type: number
    academics-additionalgpa-getgpacourse-request:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-getgpacourse-request-payload
    cmc-nexus-academics-services-studentGpaCourse:
      properties:
        id:
          format: int32
          type: number
        isTransfer:
          type: boolean
        isCumulativeGpa:
          type: boolean
        isTermGpa:
          type: boolean
        isCumulativeGpaByDefault:
          type: boolean
        isTermGpaByDefault:
          type: boolean
        isIncludedByDefault:
          type: boolean
        isManualOverride:
          type: boolean
        isRemovedByRetake:
          type: boolean
        code:
          type: string
        name:
          type: string
        term:
          type: string
        section:
          type: string
        numericGrade:
          format: double
          type: number
        grade:
          type: string
        status:
          type: string
        endDate:
          format: date-time
          type: string
        unitsEarned:
          format: double
          type: number
        unitsAttempted:
          format: double
          type: number
        gradePoints:
          format: double
          type: number
        qualityPoints:
          format: double
          type: number
        qualityUnits:
          format: double
          type: number
    cmc-core-eventing-validationMessage:
      properties:
        message:
          type: string
        messageType:
          format: int32
          type: number
    cmc-core-eventing-validationMessageCollection:
      properties:
        hasErrors:
          type: boolean
        count:
          format: int32
          type: number
        item:
          $ref: '#/components/schemas/cmc-core-eventing-validationMessage'
    academics-additionalgpa-getgpacourse-response-payload-data:
      description: ''
      properties:
        gpaName:
          type: string
        isIncludedPreviousEducationTotal:
          type: boolean
        isIncludedTermCalculation:
          type: boolean
        cumulativeGpa:
          format: double
          type: number
        studentGpaCourseList:
          type: array
          items:
            $ref: '#/components/schemas/cmc-nexus-academics-services-studentGpaCourse'
        validationMessages:
          $ref: '#/components/schemas/cmc-core-eventing-validationMessageCollection'
    academics-additionalgpa-getgpacourse-response-payload:
      properties:
        data:
          $ref: >-
            #/components/schemas/academics-additionalgpa-getgpacourse-response-payload-data
    academics-additionalgpa-getgpacourse-response:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-getgpacourse-response-payload
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
    academics-additionalgpa-getstudentgpa-request-payload:
      description: ''
      properties:
        studentId:
          format: int32
          type: number
    academics-additionalgpa-getstudentgpa-request:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-getstudentgpa-request-payload
    cmc-nexus-academics-services-studentTermGpa:
      properties:
        id:
          format: int32
          type: number
        startDate:
          format: date-time
          type: string
        endDate:
          format: date-time
          type: string
        parentTermId:
          format: int32
          type: number
        code:
          type: string
        name:
          type: string
        currentGpa:
          format: double
          type: number
        cumulativeGpa:
          format: double
          type: number
        unitsEarned:
          format: double
          type: number
        unitsAttempted:
          format: double
          type: number
        qualityPoints:
          format: double
          type: number
        qualityUnits:
          format: double
          type: number
        gradePoints:
          format: double
          type: number
        coursesTaken:
          format: int32
          type: number
    cmc-nexus-academics-services-studentGpa:
      properties:
        id:
          format: int32
          type: number
        code:
          type: string
        name:
          type: string
        isWeighted:
          type: boolean
        isShownOnDegreeProgressAudit:
          type: boolean
        isIncludedPreviousEducationTotal:
          type: boolean
        isIncludedTermCalculations:
          type: boolean
        isNoteVisible:
          type: boolean
        note:
          type: string
        studentTermGpaList:
          type: array
          items:
            $ref: '#/components/schemas/cmc-nexus-academics-services-studentTermGpa'
        cumulativeGpa:
          format: double
          type: number
        unitsEarned:
          format: double
          type: number
        unitsAttempted:
          format: double
          type: number
        qualityPoints:
          format: double
          type: number
        qualityUnits:
          format: double
          type: number
        gradePoints:
          format: double
          type: number
        coursesTaken:
          format: int32
          type: number
        cumulativeGpaText:
          type: string
    academics-additionalgpa-getstudentgpa-response-payload-data:
      description: ''
      properties:
        studentGpaList:
          type: array
          items:
            $ref: '#/components/schemas/cmc-nexus-academics-services-studentGpa'
        validationMessages:
          $ref: '#/components/schemas/cmc-core-eventing-validationMessageCollection'
    academics-additionalgpa-getstudentgpa-response-payload:
      properties:
        data:
          $ref: >-
            #/components/schemas/academics-additionalgpa-getstudentgpa-response-payload-data
    academics-additionalgpa-getstudentgpa-response:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-getstudentgpa-response-payload
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
    academics-additionalgpa-recalculategpa-request-payload:
      description: ''
      properties:
        studentId:
          format: int32
          type: number
    academics-additionalgpa-recalculategpa-request:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-recalculategpa-request-payload
    academics-additionalgpa-recalculategpa-response-payload-data:
      description: ''
      properties:
        studentGpaList:
          type: array
          items:
            $ref: '#/components/schemas/cmc-nexus-academics-services-studentGpa'
        validationMessages:
          $ref: '#/components/schemas/cmc-core-eventing-validationMessageCollection'
    academics-additionalgpa-recalculategpa-response-payload:
      properties:
        data:
          $ref: >-
            #/components/schemas/academics-additionalgpa-recalculategpa-response-payload-data
    academics-additionalgpa-recalculategpa-response:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-recalculategpa-response-payload
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
    cmc-nexus-academics-services-studentGpaCourseValue:
      properties:
        id:
          format: int32
          type: number
        isIncludedInDefaultGpa:
          type: boolean
        isIncludedInTermGpa:
          type: boolean
        isIncludeInCumGpa:
          type: boolean
        isManualOverride:
          type: boolean
        unitsAttempted:
          format: double
          type: number
        unitsEarned:
          format: double
          type: number
    academics-additionalgpa-savegpacourse-request-payload:
      description: ''
      properties:
        gpaCalculationTypeId:
          format: int32
          type: number
        studentId:
          format: int32
          type: number
        studentGpaCourseValueList:
          type: array
          items:
            $ref: >-
              #/components/schemas/cmc-nexus-academics-services-studentGpaCourseValue
    academics-additionalgpa-savegpacourse-request:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-savegpacourse-request-payload
    academics-additionalgpa-savegpacourse-response-payload-data:
      description: ''
      properties:
        calculatedGpaResponse:
          type: string
        validationMessages:
          $ref: '#/components/schemas/cmc-core-eventing-validationMessageCollection'
    academics-additionalgpa-savegpacourse-response-payload:
      properties:
        data:
          $ref: >-
            #/components/schemas/academics-additionalgpa-savegpacourse-response-payload-data
    academics-additionalgpa-savegpacourse-response:
      properties:
        payload:
          $ref: >-
            #/components/schemas/academics-additionalgpa-savegpacourse-response-payload
        notifications:
          type: array
          items: {}
        hasError:
          default: false
          type: boolean
        hasFault:
          default: false
          type: boolean
        hasWarning:
          default: false
          type: boolean
        hasValidationError:
          default: false
          type: boolean
        hasValidationWarning:
          default: false
          type: boolean
        hasValidationInformation:
          default: false
          type: boolean
        hasSecurityError:
          default: false
          type: boolean
